# Generated by Django 2.1b1 on 2018-10-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
